### ISSUE TITLE
Render server should use revelry-components from npm instead of GitHub

### ISSUE THREAD

**Issue by grossvogel** [revelrylabs/timekeeper#1]
The [render-server/package.json](https://github.com/revelrylabs/timekeeper/blob/552ad4bc231bed88f4857d891cbbe251d82c2b44/render-server/package.json) should use version `^2.0.2` of `revelry-components` from npm instead of the current github reference. The [master branch](https://github.com/revelrylabs/possum) of `revelrylabs/revelry_core_node` is now on v3, which is backwards incompatible. (The repo has also been renamed.)

**Comment by prehnRA** [comment]
Upgraded!
